[package]
name = "gins-rules-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.43", features = ["full"] }
walkdir = "2.5"
anyhow = "1.0"
which = "7.0"
regex = "1.11"
itertools = "0.14"
rayon = "1.10"
chrono = "0.4"
maxminddb = "0.24"
prost = "0.13"
maxminddb-writer = "0.1.2"
prost-derive = "0.14.3"
