import Foundation
import Yams

public enum RuleCompiler {
  /// Compiles rules into the Sing-box JSON format.
  public static func toSingBoxJSON(name: String, rules: Rules, outURL: URL) throws {
    let rs = SingBoxRuleSet(
      version: 1,
      rules: [
        SingBoxRule(
          domainSuffix: rules.domainSuffix.isEmpty ? nil : rules.domainSuffix.sorted(),
          domain: rules.domain.isEmpty ? nil : rules.domain.sorted(),
          domainKeyword: rules.domainKeyword.isEmpty ? nil : rules.domainKeyword.sorted(),
          domainRegex: rules.domainRegex.isEmpty ? nil : rules.domainRegex.sorted(),
          ipCidr: rules.ipCidr.isEmpty ? nil : rules.ipCidr.sorted(),
          processName: rules.processName.isEmpty ? nil : rules.processName.sorted(),
          userAgent: rules.userAgent.isEmpty ? nil : rules.userAgent.sorted()
        )
      ])

    let encoder = JSONEncoder()
    encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
    try encoder.encode(rs).write(to: outURL.appending(path: "\(name).json"))
  }

  /// Compiles rules into the Mihomo (Clash) YAML format.
  public static func toMihomoYAML(name: String, rules: Rules, outURL: URL, mode: MihomoRuleMode)
    throws
  {
    var payload: [String] = []

    switch mode.behavior {
    case "classical":
      payload.formUnion(rules.domainSuffix.sorted().map { "DOMAIN-SUFFIX,\($0)" })
      payload.formUnion(rules.domain.sorted().map { "DOMAIN,\($0)" })
      payload.formUnion(rules.domainKeyword.sorted().map { "DOMAIN-KEYWORD,\($0)" })
      payload.formUnion(rules.domainRegex.sorted().map { "DOMAIN-REGEXP,\($0)" })
      payload.formUnion(
        rules.ipCidr.sorted().map { "\($0.contains(":") ? "IP-CIDR6" : "IP-CIDR"),\($0)" })
      payload.formUnion(rules.ipAsn.sorted().map { "IP-ASN,\($0)" })
      payload.formUnion(rules.processName.sorted().map { "PROCESS-NAME,\($0)" })
      payload.formUnion(rules.userAgent.sorted().map { "USER-AGENT,\($0)" })
    case "ipcidr":
      payload = rules.ipCidr.sorted()
    default:  // domain
      payload = (rules.domainSuffix.formUnion(rules.domain))
        .filter { $0.components(separatedBy: ".").count <= 5 }
        .sorted()
    }

    let header = "# Gins-Rules: \(name)\n# Generated by Swift Engine (2026)\n\n"
    let yaml = try Yams.dump(object: ["payload": payload])
    try (header + yaml).write(
      to: outURL.appending(path: "\(name).yaml"), atomically: true, encoding: .utf8)
  }

  /// Detects the optimal Mihomo rule behavior based on content.
  public static func detectMihomoMode(rules: Rules, isIP: Bool) -> MihomoRuleMode {
    if !rules.processName.isEmpty || !rules.userAgent.isEmpty || !rules.ipAsn.isEmpty
      || (!rules.ipCidr.isEmpty && !rules.domainSuffix.isEmpty)
    {
      return MihomoRuleMode(behavior: "classical")
    }
    return isIP ? MihomoRuleMode(behavior: "ipcidr") : MihomoRuleMode(behavior: "domain")
  }

  /// Exports as a simple plain text list.
  public static func toPlainList(name: String, rules: Rules, outURL: URL, isIP: Bool) throws {
    var lines: [String] = []
    lines.append(contentsOf: rules.domainSuffix.sorted().map { "DOMAIN-SUFFIX,\($0)" })
    lines.append(contentsOf: rules.domain.sorted().map { "DOMAIN,\($0)" })
    lines.append(
      contentsOf: rules.ipCidr.sorted().map { "\($0.contains(":") ? "IP-CIDR6" : "IP-CIDR"),\($0)" }
    )

    let fileURL = outURL.appending(path: "\(name)\(isIP ? ".ip.list" : ".list")")
    try (lines.joined(separator: "\n") + "\n").write(to: fileURL, atomically: true, encoding: .utf8)
  }
}

extension Array where Element == String {
  fileprivate mutating func formUnion(_ other: [String]) {
    self.append(contentsOf: other)
  }
}
