[package]
name = "Gins-Rules-Core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
rmp-serde = { workspace = true }
serde_yaml = { workspace = true }
ecow = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
byteorder = { workspace = true }
prost = { workspace = true }
reqwest = { workspace = true }
